import React, { useState, useCallback } from 'react';
import FormInput from './components/FormInput';
import FormTextarea from './components/FormTextarea';
import FormSelect from './components/FormSelect';
import Loader from './components/Loader';
import { LessonPlanFormData, DailyLessonLogOutput, DayProcedures } from './types';
import { generateLessonLog } from './services/geminiService';

const App: React.FC = () => {
  const [apiKey, setApiKey] = useState<string>(''); // New state for API key
  const [formData, setFormData] = useState<LessonPlanFormData>({
    gradeLevel: '',
    quarter: '',
    subject: '',
    weeklyContentTopic: '',
    contentStandard: '',
    performanceStandard: '',
    weeklyLearningCompetency: '',
    mondayTopic: '',
    tuesdayTopic: '',
    wednesdayTopic: '',
    thursdayTopic: '',
    fridayTopic: '',
    planDuration: '5 Days (Mon - Fri)',
  });

  const [generatedDll, setGeneratedDll] = useState<DailyLessonLogOutput | null>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  const planDurationOptions = [
    { value: '5 Days (Mon - Fri)', label: '5 Days (Mon - Fri)' },
  ];

  const handleChange = useCallback((e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    // Special handling for API key
    if (name === 'apiKey') {
      setApiKey(value);
    } else {
      setFormData((prevData) => ({
        ...prevData,
        [name]: value,
      }));
    }
  }, []);

  const constructPrompt = useCallback((data: LessonPlanFormData): string => {
    const dailyTopics = {
      monday: data.mondayTopic,
      tuesday: data.tuesdayTopic,
      wednesday: data.wednesdayTopic,
      thursday: data.thursdayTopic,
      friday: data.fridayTopic,
    };

    const dailyTopicHints = Object.entries(dailyTopics)
      .filter(([, topic]) => topic)
      .map(([day, topic]) => `${day.charAt(0).toUpperCase() + day.slice(1)}'s specific focus: "${topic}".`)
      .join('\n');

    return `Generate a detailed 5-day Daily Lesson Log (Monday to Friday) based on the DepEd Philippines format.
    Provide the output in JSON format, strictly adhering to the specified schema, with detailed and concise entries for each section.

    **User-Provided Core Information:**
    Grade Level: ${data.gradeLevel}
    Quarter: ${data.quarter}
    Subject: ${data.subject}
    Weekly Content (Topic/Focus): ${data.weeklyContentTopic}

    **Weekly Plan Details (Standards and Competencies):**
    A. Content Standard: ${data.contentStandard}
    B. Performance Standard: ${data.performanceStandard}
    C. Learning Competency (LC Code): ${data.weeklyLearningCompetency}
    
    **Optional Daily Focus Hints (use these if provided):**
    ${dailyTopicHints || 'No specific daily topics provided. Infer from weekly content and progress logically through the week.'}

    **Instructions for AI-generated content (These fields are NOT user-provided and MUST be generated by AI based on the core information above and inferring weekly/daily progression):**
    - For 'school', 'teacher', and 'teachingDatesAndTime', **return an empty string ("")**. Do not generate any content for these fields; they should be left blank in the output.
    - **Learning Area:** Infer the learning area based on the subject and grade level.
    - **D. Learning Objectives (Weekly):** For each day (Monday-Friday), generate a specific, measurable, achievable, relevant, and time-bound (SMART) learning objective that progresses through the week's content, tailored to the overall weekly objectives and any provided daily topic hints.
    - **II. CONTENT (Topic):** For each day (Monday-Friday), provide the exact daily content topic, inferring it from the Weekly Content Topic and the optional daily topic hints.
    - **III. LEARNING RESOURCES - A. References:** For each day (Monday-Friday), generate relevant references (e.g., textbook pages, curriculum guide codes, online resources) that might differ or progress daily.
    - **III. LEARNING RESOURCES - B. Other Resources:** For each day (Monday-Friday), generate other appropriate learning resources (e.g., instructional materials, visual aids, technology tools) that might differ or progress daily.
    - **IV. PROCEDURES (A-J):** For each day (Monday-Friday) and for each of the 10 'procedures' sections, generate a detailed, step-by-step description of the activities, discussions, or tasks. Ensure these procedures align with the generated daily objective, content, and standards for that specific day, taking into account any provided daily topic hints.
    - Keep each generated section's content concise but informative, using clear language suitable for a lesson log.
    - Reflect the user-provided input values for `gradeLevel`, `quarter`, `subject`, `contentStandard`, `performanceStandard`, `learningCompetency`, and `weeklyContentTopic` in the JSON output as they were provided.
    `;
  }, []);

  const handleSubmit = useCallback(async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setGeneratedDll(null);

    if (!apiKey) {
      setError("Please enter your Gemini API Key before generating the lesson log.");
      setLoading(false);
      return;
    }

    const prompt = constructPrompt(formData);

    try {
      // Use 'gemini-2.5-flash' as the default model for text tasks
      const response = await generateLessonLog({ model: 'gemini-2.5-flash', prompt }, apiKey); // Pass API key
      const parsedOutput: DailyLessonLogOutput = JSON.parse(response.text);
      setGeneratedDll(parsedOutput);
    } catch (err) {
      console.error('Error during DLL generation:', err);
      setError(`Failed to generate lesson log: ${(err as Error).message}. Please ensure all required fields are filled and a valid API key is provided.`);
      setGeneratedDll(null); // Clear previous output on error
    } finally {
      setLoading(false);
    }
  }, [formData, constructPrompt, apiKey]); // Added apiKey to dependency array

  const days = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'];
  const procedureKeys: (keyof DayProcedures)[] = [
    'reviewNewLesson',
    'establishingPurposeMotivation',
    'presentingExamplesInstances',
    'discussingNewConcepts1',
    'discussingNewConcepts2',
    'developingMasteryFormativeAssessment',
    'practicalApplicationOfConcepts',
    'makingGeneralizationsAbstractions',
    'evaluatingLearningAssessment',
    'additionalActivitiesRemediation',
  ];

  const procedureLabels = {
    reviewNewLesson: 'A. Review/New Lesson',
    establishingPurposeMotivation: 'B. Establishing a purpose (Motivation)',
    presentingExamplesInstances: 'C. Presenting examples/instances',
    discussingNewConcepts1: 'D. Discussing new concepts (#1)',
    discussingNewConcepts2: 'E. Discussing new concepts (#2)',
    developingMasteryFormativeAssessment: 'F. Developing mastery (Formative Assessment)',
    practicalApplicationOfConcepts: 'G. Practical application of concepts',
    makingGeneralizationsAbstractions: 'H. Making generalizations/abstractions',
    evaluatingLearningAssessment: 'I. Evaluating learning (Assessment)',
    additionalActivitiesRemediation: 'J. Additional activities/remediation',
  };

  const generateHtmlContent = useCallback((data: DailyLessonLogOutput, currentFormData: LessonPlanFormData) => {
    // FIX: Destructure properties from currentFormData and data to ensure they are recognized as local variables,
    // addressing "Cannot find name" errors reported by the linter/compiler.
    const {
      gradeLevel: formDataGradeLevel,
      quarter: formDataQuarter,
      subject: formDataSubject,
      weeklyContentTopic: formDataWeeklyContentTopic,
    } = currentFormData;

    const {
      school,
      teacher,
      teachingDatesAndTime,
      learningArea,
      contentStandard: dllContentStandard,
      performanceStandard: dllPerformanceStandard,
      learningCompetency: dllLearningCompetency,
      weeklyLearningObjectives,
      contentTopic,
      learningResources,
      procedures,
    } = data;

    const headerTableHtml = `
      <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 10px;">
        <div style="font-weight: bold; font-size: 10pt; width: 15%; text-align: left; vertical-align: middle;">K to 10<br>DAILY LESSON LOG</div>
        <div style="width: 85%;">
          <table style="width: 100%; border-collapse: collapse; font-size: 8pt; table-layout: fixed;" class="header-table">
            <tr>
              <th colspan="2" style="width: 50%; height: 20px; border: 1px solid black; padding: 2px 4px; text-align: center; vertical-align: middle;"></th>
              <th style="width: 15%; height: 20px; border: 1px solid black; padding: 2px 4px; text-align: center; vertical-align: middle;">Grade Level</th>
              <td style="width: 35%; height: 20px; border: 1px solid black; padding: 2px 4px; text-align: left; vertical-align: middle;">${formDataGradeLevel || ''}</td>
            </tr>
            <tr>
              <td style="width: 15%; height: 20px; border: 1px solid black; padding: 2px 4px; text-align: left; vertical-align: middle;">School</td>
              <td style="width: 35%; height: 20px; border: 1px solid black; padding: 2px 4px; text-align: left; vertical-align: middle;">${school || ''}</td>
              <td style="15%; height: 20px; border: 1px solid black; padding: 2px 4px; text-align: left; vertical-align: middle;">Learning Area</td>
              <td style="width: 35%; height: 20px; border: 1px solid black; padding: 2px 4px; text-align: left; vertical-align: middle;">${learningArea || ''}</td>
            </tr>
            <tr>
              <td style="width: 15%; height: 20px; border: 1px solid black; padding: 2px 4px; text-align: left; vertical-align: middle;">Teacher</td>
              <td style="width: 35%; height: 20px; border: 1px solid black; padding: 2px 4px; text-align: left; vertical-align: middle;">${teacher || ''}</td>
              <td style="width: 15%; height: 20px; border: 1px solid black; padding: 2px 4px; text-align: center; vertical-align: middle;">Quarter</td>
              <td style="width: 35%; height: 20px; border: 1px solid black; padding: 2px 4px; text-align: left; vertical-align: middle;">${formDataQuarter || ''}</td>
            </tr>
            <tr>
              <td style="width: 15%; height: 20px; border: 1px solid black; padding: 2px 4px; text-align: left; vertical-align: middle;">Teaching Dates and Time</td>
              <td colspan="3" style="height: 20px; border: 1px solid black; padding: 2px 4px; text-align: left; vertical-align: middle;">${teachingDatesAndTime || ''}</td>
            </tr>
          </table>
        </div>
      </div>
    `;

    const mainTableHtml = `
      <table style="width: 100%; border-collapse: collapse; font-size: 8pt; table-layout: fixed;" class="objectives-procedures-table">
          <thead>
              <tr>
                  <th style="width: 15%; vertical-align: middle;">OBJECTIVES/PROCEDURES</th>
                  <th style="width: 17%; vertical-align: middle;">MONDAY</th>
                  <th style="width: 17%; vertical-align: middle;">TUESDAY</th>
                  <th style="width: 17%; vertical-align: middle;">WEDNESDAY</th>
                  <th style="width: 17%; vertical-align: middle;">THURSDAY</th>
                  <th style="width: 17%; vertical-align: middle;">FRIDAY</th>
              </tr>
          </thead>
          <tbody>
              <tr>
                  <td style="padding: 2px 4px; border: 1px solid black; font-weight: bold; vertical-align: top;">I. OBJECTIVES</td>
                  <td colspan="5" style="padding: 2px 4px; border: 1px solid black; vertical-align: top;"></td>
              </tr>
              <tr>
                  <td style="padding: 2px 4px; border: 1px solid black; padding-left: 8px; vertical-align: top;">A. Content Standard</td>
                  <td colspan="5" style="padding: 2px 4px; border: 1px solid black; vertical-align: top;">${dllContentStandard || ''}</td>
              </tr>
              <tr>
                  <td style="padding: 2px 4px; border: 1px solid black; padding-left: 8px; vertical-align: top;">B. Performance Standard</td>
                  <td colspan="5" style="padding: 2px 4px; border: 1px solid black; vertical-align: top;">${dllPerformanceStandard || ''}</td>
              </tr>
              <tr>
                  <td style="padding: 2px 4px; border: 1px solid black; padding-left: 8px; vertical-align: top;">C. Learning Competency (LC Code)</td>
                  <td colspan="5" style="padding: 2px 4px; border: 1px solid black; vertical-align: top;">${dllLearningCompetency || ''}</td>
              </tr>
              <tr>
                  <td style="padding: 2px 4px; border: 1px solid black; padding-left: 8px; vertical-align: top;">D. Learning Objectives (Weekly)</td>
                  ${days.map(day => `<td style="padding: 2px 4px; border: 1px solid black; vertical-align: top;">${weeklyLearningObjectives?.[day as keyof DailyLessonLogOutput['weeklyLearningObjectives']] || ''}</td>`).join('')}
              </tr>
              <tr>
                  <td style="padding: 2px 4px; border: 1px solid black; font-weight: bold; vertical-align: top;">II. CONTENT (Topic)</td>
                  ${days.map(day => `<td style="padding: 2px 4px; border: 1px solid black; vertical-align: top;">${contentTopic?.[day as keyof DailyLessonLogOutput['contentTopic']] || ''}</td>`).join('')}
              </tr>
              <tr>
                  <td style="padding: 2px 4px; border: 1px solid black; font-weight: bold; vertical-align: top;">III. LEARNING RESOURCES</td>
                  <td colspan="5" style="padding: 2px 4px; border: 1px solid black; vertical-align: top;"></td>
              </tr>
              <tr>
                  <td style="padding: 2px 4px; border: 1px solid black; padding-left: 8px; vertical-align: top;">A. References</td>
                  ${days.map(day => `<td style="padding: 2px 4px; border: 1px solid black; vertical-align: top;">${learningResources?.references?.[day as keyof DailyLessonLogOutput['learningResources']['references']] || ''}</td>`).join('')}
              </tr>
              <tr>
                  <td style="padding: 2px 4px; border: 1px solid black; padding-left: 8px; vertical-align: top;">B. Other Resources</td>
                  ${days.map(day => `<td style="padding: 2px 4px; border: 1px solid black; vertical-align: top;">${learningResources?.otherResources?.[day as keyof DailyLessonLogOutput['learningResources']['otherResources']] || ''}</td>`).join('')}
              </tr>
              <tr>
                  <td style="padding: 2px 4px; border: 1px solid black; font-weight: bold; vertical-align: top;">IV. PROCEDURES</td>
                  <td colspan="5" style="padding: 2px 4px; border: 1px solid black; vertical-align: top;"></td>
              </tr>
              ${procedureKeys.map(key => `
                  <tr>
                      <td style="padding: 2px 4px; border: 1px solid black; padding-left: 8px; vertical-align: top;">${procedureLabels[key]}</td>
                      ${days.map(day => `<td style="padding: 2px 4px; border: 1px solid black; vertical-align: top;">${procedures?.[day as keyof DailyLessonLogOutput['procedures']]?.[key] || ''}</td>`).join('')}
                  </tr>
              `).join('')}
          </tbody>
      </table>
    `;

    const footerHtml = `
      <div style="display: flex; justify-content: space-between; align-items: flex-end; font-size: 8pt; margin-top: 20px; padding: 5px;">
        <div style="display: flex; flex-direction: column;">
          <span>Prepared by:</span>
          <span style="margin-top: 10px; border-bottom: 1px solid black; padding: 0 20px; text-align: center; font-weight: bold;">${teacher || ''}</span>
          <span style="text-align: center;">Teacher</span>
        </div>
        <div style="display: flex; flex-direction: column;">
          <span>Inspected:</span>
          <span style="margin-top: 10px; border-bottom: 1px solid black; padding: 0 20px; text-align: center;"></span>
          <span style="text-align: center;">Immediate Supervisor</span>
        </div>
      </div>
    `;

    return `
      <!DOCTYPE html>
      <html lang="en">
      <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Daily Lesson Log - ${formDataWeeklyContentTopic || 'Lesson Log'}</title>
          <style>
              body {
                  font-family: Arial, sans-serif;
                  margin: 0;
                  padding: 0;
                  box-sizing: border-box;
                  background-color: #f9f9f9;
              }
              .page-container {
                  width: 28cm; /* A4 landscape width */
                  min-height: 19cm; /* A4 landscape height */
                  margin: 1cm auto;
                  padding: 1cm;
                  border: 1px solid #ccc;
                  background-color: #fff;
                  box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
              }
              table {
                  width: 100%;
                  border-collapse: collapse;
                  margin-bottom: 10px;
                  font-size: 8pt;
              }
              th, td {
                  border: 1px solid black;
                  padding: 3px 5px;
                  text-align: left;
                  vertical-align: top;
              }
              th {
                  background-color: #e0e0e0;
                  font-weight: bold;
                  text-align: center;
              }
              /* Print specific styles for landscape A4 */
              @page {
                  size: A4 landscape;
                  margin: 1cm;
              }
          </style>
      </head>
      <body>
          <div class="page-container">
              ${headerTableHtml}
              ${mainTableHtml}
              ${footerHtml}
            </div>
          </body>
          </html>
        `;
  }, [days, procedureKeys, procedureLabels]);

  const downloadAsWord = useCallback(() => {
    if (!generatedDll) return;
    // Pass formData to generateHtmlContent to source user-provided input values
    const htmlContent = generateHtmlContent(generatedDll, formData);
    const blob = new Blob([htmlContent], {
      type: 'application/msword',
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Daily_Lesson_Log_Grade_${formData.gradeLevel || 'N/A'}_${formData.subject || 'N/A'}_${formData.weeklyContentTopic || 'Lesson'}_5_Days.doc`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [generatedDll, generateHtmlContent, formData]); // Added formData to dependency array

  // Reusable style object for DLL table cells in JSX preview
  const dllTableCellBaseStyle: React.CSSProperties = {
    padding: '5px 8px',
    border: '1px solid black',
    verticalAlign: 'top', // Corrected to camelCase
    textAlign: 'left',
  };

  const dllTableHeaderStyle: React.CSSProperties = {
    ...dllTableCellBaseStyle,
    fontWeight: 'bold',
    textAlign: 'center',
    backgroundColor: '#e0e0e0',
    verticalAlign: 'middle', // Corrected to camelCase
  };


  return (
    <div className="min-h-screen bg-gray-100 p-4">
      <h1 className="text-4xl font-extrabold text-center text-blue-800 mb-2"> {/* Changed mb-8 to mb-2 for spacing */}
        Medina IS Daily Lesson Log Generator
      </h1>
      <p className="text-sm text-gray-600 text-center mb-8"> {/* New line added */}
        Powered by Gemini 2.5 Flash | Created by: Jonard T. Tejones
      </p>

      <form onSubmit={handleSubmit} className="bg-white p-6 rounded-lg shadow-md mb-8">
        <div className="mb-6">
          <FormInput
            id="apiKey"
            label="Gemini API Key"
            value={apiKey}
            onChange={handleChange}
            placeholder="Enter your Gemini API Key"
            required
            className="col-span-full"
          />
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
          <FormSelect
            id="gradeLevel"
            label="Grade Level"
            value={formData.gradeLevel}
            onChange={handleChange}
            options={[
              { value: '', label: 'Select Grade Level' },
              { value: 'Kindergarten', label: 'Kindergarten' },
              { value: 'Grade 1', label: 'Grade 1' },
              { value: 'Grade 2', label: 'Grade 2' },
              { value: 'Grade 3', label: 'Grade 3' },
              { value: 'Grade 4', label: 'Grade 4' },
              { value: 'Grade 5', label: 'Grade 5' },
              { value: 'Grade 6', label: 'Grade 6' },
              { value: 'Grade 7', label: 'Grade 7' },
              { value: 'Grade 8', label: 'Grade 8' },
              { value: 'Grade 9', label: 'Grade 9' },
              { value: 'Grade 10', label: 'Grade 10' },
              { value: 'Grade 11', label: 'Grade 11' },
              { value: 'Grade 12', label: 'Grade 12' },
            ]}
            required
          />
          <FormSelect
            id="quarter"
            label="Quarter"
            value={formData.quarter}
            onChange={handleChange}
            options={[
              { value: '', label: 'Select Quarter' },
              { value: '1st Quarter', label: '1st Quarter' },
              { value: '2nd Quarter', label: '2nd Quarter' },
              { value: '3rd Quarter', label: '3rd Quarter' },
              { value: '4th Quarter', label: '4th Quarter' },
            ]}
            required
          />
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
          <FormInput
            id="subject"
            label="Subject"
            value={formData.subject}
            onChange={handleChange}
            placeholder="e.g., Science, Mathematics, English"
            required
          />
          <FormInput
            id="weeklyContentTopic"
            label="Weekly Content Topic"
            value={formData.weeklyContentTopic}
            onChange={handleChange}
            placeholder="e.g., The Solar System, Fractions, Philippine History"
            required
          />
        </div>

        <div className="mb-6">
          <FormTextarea
            id="contentStandard"
            label="Content Standard"
            value={formData.contentStandard}
            onChange={handleChange}
            placeholder="e.g., The learners demonstrate understanding of the solar system."
            rows={2}
            required
          />
        </div>
        <div className="mb-6">
          <FormTextarea
            id="performanceStandard"
            label="Performance Standard"
            value={formData.performanceStandard}
            onChange={handleChange}
            placeholder="e.g., The learners shall be able to describe the components of the solar system."
            rows={2}
            required
          />
        </div>
        <div className="mb-6">
          <FormTextarea
            id="weeklyLearningCompetency"
            label="C. Learning Competency (LC Code)"
            value={formData.weeklyLearningCompetency}
            onChange={handleChange}
            placeholder="e.g., S5FE-IVa-1: Describe the components of the solar system."
            rows={2}
            required
          />
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
          <FormInput
            id="mondayTopic"
            label="Monday's Specific Topic (Optional)"
            value={formData.mondayTopic}
            onChange={handleChange}
            placeholder="e.g., The Sun and its Characteristics"
          />
          <FormInput
            id="tuesdayTopic"
            label="Tuesday's Specific Topic (Optional)"
            value={formData.tuesdayTopic}
            onChange={handleChange}
            placeholder="e.g., The Inner Planets"
          />
          <FormInput
            id="wednesdayTopic"
            label="Wednesday's Specific Topic (Optional)"
            value={formData.wednesdayTopic}
            onChange={handleChange}
            placeholder="e.g., The Outer Planets"
          />
          <FormInput
            id="thursdayTopic"
            label="Thursday's Specific Topic (Optional)"
            value={formData.thursdayTopic}
            onChange={handleChange}
            placeholder="e.g., Asteroids, Comets, and Meteors"
          />
          <FormInput
            id="fridayTopic"
            label="Friday's Specific Topic (Optional)"
            value={formData.fridayTopic}
            onChange={handleChange}
            placeholder="e.g., Review and Assessment"
          />
          <FormSelect
            id="planDuration"
            label="Plan Duration"
            value={formData.planDuration}
            onChange={handleChange}
            options={planDurationOptions}
            required
          />
        </div>

        <button
          type="submit"
          disabled={loading}
          className="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 px-4 rounded-md transition duration-300 ease-in-out flex items-center justify-center disabled:opacity-50"
        >
          {loading ? (
            <>
              <svg className="animate-spin h-5 w-5 mr-3 text-white" viewBox="0 0 24 24"></svg>
              Generating...
            </>
          ) : (
            'Generate Daily Lesson Log'
          )}
        </button>
      </form>

      {loading && <Loader message="Generating your 5-Day Daily Lesson Log..." />}
      {error && (
        <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-8" role="alert">
          <strong className="font-bold">Error!</strong>
          <span className="block sm:inline"> {error}</span>
        </div>
      )}

      {generatedDll && (
        <div className="bg-white p-6 rounded-lg shadow-md mt-8">
          <h2 className="text-2xl font-bold text-blue-800 mb-4">Generated 5-Day Daily Lesson Log</h2>
          {/* Display the generated DLL content on the page, using React JSX for rendering */}
          <div className="overflow-x-auto">
            {/* Increased min-width to accommodate 6 columns in landscape preview */}
            <div style={{ minWidth: '1600px', margin: '0 auto', padding: '1cm', border: '1px solid #ccc', backgroundColor: '#fff', boxShadow: '0 0 10px rgba(0, 0, 0, 0.1)' }}>
              {/* Header Table */}
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '10px' }}>
                <div style={{ fontWeight: 'bold', fontSize: '12pt', flexShrink: 0, width: '15%', textAlign: 'left', verticalAlign: 'middle' }}>K to 10<br/>DAILY LESSON LOG</div>
                <div style={{ width: '85%' }}>
                  <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '10pt', tableLayout: 'fixed' }} className="header-table">
                      <tr>
                          <th colSpan={2} style={{ width: '50%', height: '25px', border: '1px solid black', padding: '5px 8px', textAlign: 'center', verticalAlign: 'middle' }}></th>
                          <th style={{ width: '12%', height: '25px', border: '1px solid black', padding: '5px 8px', textAlign: 'center', verticalAlign: 'middle' }}>Grade Level</th>
                          <td style={{ width: '38%', height: '25px', border: '1px solid black', padding: '5px 8px', textAlign: 'left', verticalAlign: 'middle' }}>{formData.gradeLevel || ''}</td>
                      </tr>
                      <tr>
                          <td style={{ width: '12%', height: '25px', border: '1px solid black', padding: '5px 8px', textAlign: 'left', verticalAlign: 'middle' }}>School</td>
                          <td style={{ width: '38%', height: '25px', border: '1px solid black', padding: '5px 8px', textAlign: 'left', verticalAlign: 'middle' }}>{generatedDll.school || ''}</td>
                          <td style={{ width: '12%', height: '25px', border: '1px solid black', padding: '5px 8px', textAlign: 'left', verticalAlign: 'middle' }}>Learning Area</td>
                          {/* Corrected vertical-align to verticalAlign */}
                          <td style={{ width: '38%', height: '25px', border: '1px solid black', padding: '5px 8px', textAlign: 'left', verticalAlign: 'middle' }}>{generatedDll.learningArea || ''}</td>
                      </tr>
                      <tr>
                          <td style={{ width: '12%', height: '25px', border: '1px solid black', padding: '5px 8px', textAlign: 'left', verticalAlign: 'middle' }}>Teacher</td>
                          <td style={{ width: '38%', height: '25px', border: '1px solid black', padding: '5px 8px', textAlign: 'left', verticalAlign: 'middle' }}>{generatedDll.teacher || ''}</td>
                          <td style={{ width: '12%', height: '25px', border: '1px solid black', padding: '5px 8px', textAlign: 'center', verticalAlign: 'middle' }}>Quarter</td>
                          <td style={{ width: '38%', height: '25px', border: '1px solid black', padding: '5px 8px', textAlign: 'left', verticalAlign: 'middle' }}>{formData.quarter || ''}</td>
                      </tr>
                      <tr>
                          <td style={{ width: '12%', height: '25px', border: '1px solid black', padding: '5px 8px', textAlign: 'left', verticalAlign: 'middle' }}>Teaching Dates and Time</td>
                          <td colSpan={3} style={{ height: '25px', border: '1px solid black', padding: '5px 8px', textAlign: 'left', verticalAlign: 'middle' }}>{generatedDll.teachingDatesAndTime || ''}</td>
                      </tr>
                  </table>
                </div>
              </div>

              {/* Main DLL Table for 5 Days */}
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '10pt', tableLayout: 'fixed' }} className="objectives-procedures-table">
                  <thead>
                      <tr>
                          <th style={{ width: '15%' }}>OBJECTIVES/PROCEDURES</th>
                          <th style={{ width: '17%' }}>MONDAY</th>
                          <th style={{ width: '17%' }}>TUESDAY</th>
                          <th style={{ width: '17%' }}>WEDNESDAY</th>
                          <th style={{ width: '17%' }}>THURSDAY</th>
                          <th style={{ width: '17%' }}>FRIDAY</th>
                      </tr>
                  </thead>
                  <tbody>
                      <tr>
                          <td style={{ padding: '5px 8px', border: '1px solid black', fontWeight: 'bold' }}>I. OBJECTIVES</td>
                          <td colSpan={5} style={{ padding: '5px 8px', border: '1px solid black' }}></td>
                      </tr>
                      <tr>
                          <td style={{ padding: '5px 8px', border: '1px solid black', paddingLeft: '16px' }}>A. Content Standard</td>
                          <td colSpan={5} style={{ padding: '5px 8px', border: '1px solid black' }}>{generatedDll.contentStandard || ''}</td>
                      </tr>
                      <tr>
                          <td style={{ padding: '5px 8px', border: '1px solid black', paddingLeft: '16px' }}>B. Performance Standard</td>
                          <td colSpan={5} style={{ padding: '5px 8px', border: '1px solid black' }}>{generatedDll.performanceStandard || ''}</td>
                      </tr>
                      <tr>
                          <td style={{ padding: '5px 8px', border: '1px solid black', paddingLeft: '16px' }}>C. Learning Competency (LC Code)</td>
                          <td colSpan={5} style={{ padding: '5px 8px', border: '1px solid black' }}>{generatedDll.learningCompetency || ''}</td>
                      </tr>
                      <tr>
                          <td style={{ padding: '5px 8px', border: '1px solid black', paddingLeft: '16px' }}>D. Learning Objectives (Weekly)</td>
                          {days.map(day => (
                            <td key={day} style={{ padding: '5px 8px', border: '1px solid black' }}>
                              {generatedDll.weeklyLearningObjectives?.[day as keyof DailyLessonLogOutput['weeklyLearningObjectives']] || ''}
                            </td>
                          ))}
                      </tr>
                      <tr>
                          <td style={{ padding: '5px 8px', border: '1px solid black', fontWeight: 'bold' }}>II. CONTENT (Topic)</td>
                          {days.map(day => (
                            <td key={day} style={{ padding: '5px 8px', border: '1px solid black' }}>
                              {generatedDll.contentTopic?.[day as keyof DailyLessonLogOutput['contentTopic']] || ''}
                            </td>
                          ))}
                      </tr>
                      <tr>
                          <td style={{ padding: '5px 8px', border: '1px solid black', fontWeight: 'bold' }}>III. LEARNING RESOURCES</td>
                          <td colSpan={5} style={{ padding: '5px 8px', border: '1px solid black' }}></td>
                      </tr>
                      <tr>
                          <td style={{ padding: '5px 8px', border: '1px solid black', paddingLeft: '16px' }}>A. References</td>
                          {days.map(day => (
                            <td key={day} style={{ padding: '5px 8px', border: '1px solid black' }}>
                              {generatedDll.learningResources?.references?.[day as keyof DailyLessonLogOutput['learningResources']['references']] || ''}
                            </td>
                          ))}
                      </tr>
                      <tr>
                          <td style={{ padding: '5px 8px', border: '1px solid black', paddingLeft: '16px' }}>B. Other Resources</td>
                          {days.map(day => (
                            <td key={day} style={{ padding: '5px 8px', border: '1px solid black' }}>
                              {generatedDll.learningResources?.otherResources?.[day as keyof DailyLessonLogOutput['learningResources']['otherResources']] || ''}
                            </td>
                          ))}
                      </tr>
                      <tr>
                          <td style={{ padding: '5px 8px', border: '1px solid black', fontWeight: 'bold' }}>IV. PROCEDURES</td>
                          <td colSpan={5} style={{ padding: '5px 8px', border: '1px solid black' }}></td>
                      </tr>
                      {procedureKeys.map((key) => (
                          <tr key={key}>
                              <td style={{ padding: '5px 8px', border: '1px solid black', paddingLeft: '16px' }}>{procedureLabels[key]}</td>
                              {days.map(day => (
                                <td key={day} style={{ padding: '5px 8px', border: '1px solid black' }}>
                                  {generatedDll.procedures?.[day as keyof DailyLessonLogOutput['procedures']]?.[key] || ''}
                                </td>
                              ))}
                          </tr>
                      ))}
                  </tbody>
              </table>

              {/* Footer */}
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', fontSize: '10px', marginTop: '20px', padding: '5px' }}>
                <div style={{ display: 'flex', flexDirection: 'column' }}>
                  <span>Prepared by:</span>
                  <span style={{ marginTop: '16px', borderBottom: '1px solid black', padding: '0 32px', textAlign: 'center', fontWeight: 'bold' }}>{generatedDll.teacher || ''}</span>
                  <span style={{ textAlign: 'center' }}>Teacher</span>
                </div>
                <div style={{ display: 'flex', flexDirection: 'column' }}>
                  <span>Inspected:</span>
                  <span style={{ marginTop: '16px', borderBottom: '1px solid black', padding: '0 32px', textAlign: 'center' }}></span>
                  <span style={{ textAlign: 'center' }}>Immediate Supervisor</span>
                </div>
              </div>
            </div>
          </div>
          <button
            onClick={downloadAsWord}
            className="mt-6 w-full bg-green-600 hover:bg-green-700 text-white font-bold py-3 px-4 rounded-md transition duration-300 ease-in-out flex items-center justify-center"
          >
            Download as Word Document
          </button>
        </div>
      )}
    </div>
  );
};

export default App;